### ISSUE TITLE
clean up requests dependency

### ISSUE THREAD

**Issue by aclerc** [resgroup/wind-up#18]
I think requests might only be used in the examples so it's not needed in the main list of dependencies. Investigate defining an examples dependency group (maybe re-define the jupyter group) to clean this up

**Comment by izofat** [comment]
Hi. 
I fixed the issue.
I did some investigation but it didn't see usage of requests outside of examples.
Created a new group named examples.
If you think re-defining the jupyter group is better let me know.

https://github.com/resgroup/wind-up/pull/19

**Comment by aclerc** [comment]
Thank you @izofat ! PR is merged
